services:
  limitless-sync:
    build: .
    container_name: limitless-memory-sync
    restart: unless-stopped
    
    # Environment configuration
    environment:
      - DATABASE_PATH=/app/data/limitless_sync.db
      - LOG_PATH=/app/logs/
      - LOG_LEVEL=INFO
      - HEALTH_CHECK_PORT=8080
    
    # Load environment variables from .env file
    env_file:
      - .env
    
    # Volume mounts for persistence
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    
    # Port mapping for health checks
    ports:
      - "8080:8080"
    
    # Health check configuration
    healthcheck:
      test: ["CMD", "python", "health_check.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Network configuration
    networks:
      - limitless-sync-network

networks:
  limitless-sync-network:
    driver: bridge
